name: Update Heroku Database

on:
  # Trigger the workflow on push to main or at scheduled times
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the update script
    - name: Run update script
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GOOGLE_SERVICE_ACCOUNT_JSON_B64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_B64 }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        SPREADSHEET_ID: ${{secrets.SPREADSHEET_ID}}
      run: python scripts/update_database.py
